config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  root to: 'users#show'
  resources :users, only: [:new, :create]
  resources :tasks, except: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  validates :name, presence: true, length: { in: 1..256 }
  validates :completed, inclusion: { in: [true, false] }
  validate :completion_time_after_creation_time

  def completion_time_after_creation_time
    if completion_time && completion_time < created_at
      errors.add(:completion_time, "Task creation time cannot exceed task completion time.")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy

  email_regex = /\A[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,63}\z/i
  password_format = /\A.*(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#$%^&+=]).*\z/

  validates :username, uniqueness: true, presence: true, length: { in: 6..64 }
  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: email_regex }
  validates :password, format: { with: password_format,
                       message: "must contain at least 1 capital letter, 1 lowercase letter, 1 number, and 1 special character" },
                       length: { in: 6..32 },
                       allow_nil: true,
                       confirmation: true
  has_secure_password
  validates :first_name, length: { maximum: 64 }
  validates :last_name, length: { maximum: 64 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !@current_user.nil?
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :current_user

  def new
    redirect_to root_url if logged_in?
  end

  def create
    if !logged_in?
      user = User.find_by(username: params[:session][:username])
      if user && user.authenticate(params[:session][:password])
        session[:user_id] = user.id
        redirect_to root_url
      else
        flash.now[:danger] = "Your username or password does not match."
        @errors = ["Your username or password does not match."]
        render 'new'
      end
    else
      redirect_to root_url
    end
  end

  def destroy
    session.delete(:user_id) if logged_in?
    @current_user = nil
    redirect_to root_url
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :current_user

  def show
    #do i need a show task page?
  end

  def new
    if logged_in?
      @task = Task.new
    else
      redirect_to login_url
    end
  end

  def create
    @task = Task.new(task_params)
    @task.user_id = @current_user.id
    if @task.save
      flash[:success] = "Task added"
      redirect_to tasks_url
    else
      @errors = @task.errors.full_messages
      flash.now[:danger] = "Could not add task"
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
    def task_params
      params.require(:task).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :current_user

  def show
    if logged_in?
      @tasks = @current_user.tasks
    end
  end

  def new
    @user = User.new
    if logged_in?
      redirect_to root_url
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Account created."
      redirect_to root_url
    else
      @errors = @user.errors.full_messages
      flash.now[:danger] = "Could not create an account."
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation, :first_name, :last_name)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
    !@current_user.nil?
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDooey</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if errors %>
  <ul>
    <% errors.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>

app/views/tasks/_form.html.erb
<%= form_for(@task, multipart: true) do |f| %>
  <%= render partial: 'shared/errors', locals: { errors: @errors } %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit "Add this task" %>
<% end %>

app/views/tasks/new.html.erb
<h1>Create a new task</h1>
  <%= render 'form' %>

app/views/users/_form.html.erb
<%= form_for(@user, multipart: true) do |f| %>
  <%= render partial: 'shared/errors', locals: { errors: @errors } %>

  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :first_name %>
  <%= f.text_field :first_name %>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create your account" %>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>
  <%= render 'form' %>

app/views/users/show.html.erb
<h1>hello</h1>

  <% if logged_in? %>
    <!-- <ul style="list-style: none">
      <% @current_user.tasks.each do |task| %>
        <li><%= task.name %></li>
      <% end %>
    </ul> -->

    <%= react_component "Tasks", { data: @tasks } %>

  <% else %>
    <%= link_to "Log in", login_path %> or <%= link_to "Sign up!", new_user_path %>
  <% end %>